### ISSUE TITLE
pdf view 구현

### ISSUE THREAD

**Issue by etranger-park** [hangpark/kaistusc#109]
- 공약 및 정책 자료집에 사용
- 2페이지 뷰로 보여져야 한다.
- 기존 POST의 모델을 사용한다.
- 최신 POST의 attached파일을 pdf 뷰를 통해서 보여준다.
- admin 계정은 edit버튼을 통해 POST를 추가하는 방식으로 보여질 파일을 수정할 수 있다.

**Comment by jiggum** [comment]
+4

**Comment by etranger-park** [comment]
5

**Comment by ashe-sparcs** [comment]
5

**Comment by ashe-sparcs** [comment]
최종 5
