### ISSUE TITLE
격주 보고 구현

### ISSUE THREAD

**Issue by etranger-park** [hangpark/kaistusc#111]
총합 업무 탭의 한 보드 입니다. 
POST 형식을 그대로 사용해서 (혹은 확장해서), 해당 카테고리 게시물의 첨부 사진을 스와이프 형식으로 볼 수 있도록(화살표를 클릭해서 넘어가도록) 구현해야 합니다.
삭제 기능을 넣아야 합니다.

**Comment by jiggum** [comment]
+5

**Comment by etranger-park** [comment]
5

**Comment by ashe-sparcs** [comment]
5

**Comment by etranger-park** [comment]
5
