### ISSUE TITLE
모델 필드 추가 및 마이그레이션

### ISSUE THREAD

**Issue by ashe-sparcs** [hangpark/kaistusc#112]
https://docs.google.com/document/d/1DIopdEdlp6omPdTCazTu4XgaKzkEAJzMofJkTZyWfpc/edit?usp=sharing

를 참조하여 기존의 모델을 수정하고 makemigrations, migrate해서 런서버 에러 없이 성공하기.

settings.py 디비 설정을 mysql에서 sqlite로 바꿔야 함.

**Comment by ashe-sparcs** [comment]
삽질이 얼마나 될지 몰라서 우선 5로 달텐데. 해보고 삽질 없었으면 양심껏 낮추겠음.

**Comment by jiggum** [comment]
+7
기존에 존재하던 모델들을 수정할때는, 실섭 데이터의 마이그레이션이 고려되어야할것같습니다.

**Comment by etranger-park** [comment]
6

**Comment by ashe-sparcs** [comment]
달려서 오늘 안에 끝내버리기~ 해보겠습니다

**Comment by ashe-sparcs** [comment]
런서버 돌려봤고 모델 작성 중입니다. 수요일(이나 목요일 넘어가는 새벽)까지는 꼭 작성 완료하겠습니다.

**Comment by ashe-sparcs** [comment]
체감상 5보다는 쉬웠던? 느낌 4로 하겠습니다.
