### ISSUE TITLE
의결기구 오픈톡방 리다이렉팅 구현

### ISSUE THREAD

**Issue by jiggum** [hangpark/kaistusc#113]
- 중집위에서 운영하는 의결기구 오픈톡방으로 redirecting되는 배너가 필요합니다.
- basePost 상속받아 표현
- 의결기구 오픈톡방 보드 진입시 redirect 텍스트들 바로 노출
- 관리자의경우 추가/수정/삭제 가능 (관리자의경우에만 해당아이콘 노출)
-  추가/수정뷰 구현 (의결기구, url 만 인풋받도록) (기존 edit뷰에서 필요없는 버튼 가리고, 플레이스홀더변경, 인풋폼 사이즈 조정 또는 새로운 edit뷰 생성)

**Comment by jiggum** [comment]
+3

**Comment by ashe-sparcs** [comment]
4

**Comment by etranger-park** [comment]
4

**Comment by ashe-sparcs** [comment]
추가/수정/삭제 구현하고 닫을게요.

**Comment by ashe-sparcs** [comment]
4
