### ISSUE TITLE
배너, 배너 그룹 구현

### ISSUE THREAD

**Issue by ashe-sparcs** [hangpark/kaistusc#117]
<배너>
학생회 소통창구: 학과학생회 자료가 리스트로 아카이빙 되어 있고 그 바로 위에 배너 형태로 소통창구(페이스북 페이지?) 리다이렉팅.
의결기구 오픈톡방: 의결기구 자료가 리스트로 아카이빙 되어 있고 그 바로 위에 배너 형태로 의결기구 오픈톡방 리다이렉팅.
카대전/아라: 굳이 배너가 필요할까 싶음. 메뉴에서 바로 링크로 리다이렉트 하면 어떨까.

<배너 그룹>
행사와 광고 배너가 섞여진 것을 캐러슬 (https://getbootstrap.com/docs/4.0/components/carousel/) 형태로. 위치는 메인페이지 공지사항 밑으로 내리고 그 위에.

**Comment by ashe-sparcs** [comment]
5

**Comment by jiggum** [comment]
+4

**Comment by etranger-park** [comment]
3

**Comment by jiggum** [comment]
+4
