### ISSUE TITLE
국서별 사업 현황 페이지 제작

### ISSUE THREAD

**Issue by jiggum** [hangpark/kaistusc#118]
국서별로 현재 진행되는 사업의 파기여부/공약여부/사업소개/진행정도를 소개할 수 있는 탭이 필요합니다. key항목의 추가는 개발이후 필요없되, 관리자가 각 항목을 추가할 수는 있어야 합니다.
데이터 구조: 
 { title: '총학생회 비어파티',
description: '오프라인 소통사업 및 간담회 형식으로 진행되는 사업입니다. 총학생회 간부들과 함께 맥주를 마시며 시시콜콜한 이야기부터 깊은 이야기까지 나눌 수 있습니다.', // 짧은 소개글
status: 3, // 0: 상시, 1:완료, 2:파기, 3:진행중
bureau: '소통국',
isPledge: 1, // 0: 공약x, 1:공약o
alteration: [], // array of string }

- Post 모델 상속
- alteration: 진행상황의 이력
- 각 필드를 적절한 ui로 표현해주어야함
- 수정뷰에서또한 각필드별 수정폼이 존재해야함
- 관리자: 추가/수정/삭제권한
- 유저: 조회권한

**Comment by ashe-sparcs** [comment]
5

**Comment by jiggum** [comment]
+7

**Comment by etranger-park** [comment]
8

**Comment by jiggum** [comment]
#143 
+9
