### ISSUE TITLE
매점, 잡화점 물품 페이지

### ISSUE THREAD

**Issue by etranger-park** [hangpark/kaistusc#120]
- 물품에 대한 model을 사용
- 각 매점에 대한 TAB이 존재 해야 한다.
- 각 물품의 정보는 이미지 없이 이름,가격, 카테고리 이다.
- 각 탭에서 물품이 어떻게 보일지에 대한 UI는 아직 미정인 상태
- 복수 선택이 가능한 카테고리로 필터링을 할 수 있어야 한다.
- 관리자의 추가/삭제 권한이 필요하다.

**Comment by ashe-sparcs** [comment]
7

**Comment by jiggum** [comment]
+6

**Comment by etranger-park** [comment]
7

**Comment by jiggum** [comment]
7
