### ISSUE TITLE
Agora 구현

### ISSUE THREAD

**Issue by jiggum** [hangpark/kaistusc#122]
각 agenda에 대한 토론이 필요할 때 댓글로 논쟁/토론이 일어날 수 있는 항목이 필요합니다.
3명 이상의 청원 혹은 관리자가 항목을 추가할 수 있습니다.
- [관리자게시글, 논의중, 청원 필요, 완료] 상태를 게시글 리스트뷰에서 알수있도록 ui작업이 필요
- 정렬기능 [default(관리자게시글상단, 최신순), 추천수]
- 필터기능 [관리자게시글, 논의중, 청원 필요, 완료]
- 비추천은 불가능함
- 토론종결시기 필요
- Post 상속

**Comment by ashe-sparcs** [comment]
4

**Comment by jiggum** [comment]
+6

**Comment by etranger-park** [comment]
5

**Comment by etranger-park** [comment]
5
