### ISSUE TITLE
아카이빙 게시판 제작

### ISSUE THREAD

**Issue by etranger-park** [hangpark/kaistusc#126]
의결기구 자료, 학과 학생회의 자료를 아카이빙 할 수 있는 보드가 필요합니다.

의결기구 자료 아카이빙

- 의결기구는 중앙운영위원회 와 전체 학생대표자회의 로 나뉘어서 자료를 모집해야 합니다.
- 별도의 뷰어는 필요하지 않습니다. 
- 자료에 대한 설명글과 파일 첨부기능이 필요합니다. 기존 POST를 사용할 수 있을것으로 생각됩니다.
 

학부 학과 학생회 소통창구 및 자료 아카이빙

- 각 학과별 탭이 필요합니다.
- redirecting되는 배너는 배너 제작에서 이루어 질 것입니다.
- 별도의 뷰어는 필요하지 않습니다.
- 파일을 클릭하면 바로 파일 뷰로 넘어가야 합니다. (수정된 사항입니다.)
BASEPOST를 활용할 수 있을 것 같습니다.

**Comment by etranger-park** [comment]
4

**Comment by ashe-sparcs** [comment]
4

**Comment by jiggum** [comment]
3

**Comment by etranger-park** [comment]
3
