### ISSUE TITLE
post_form.jinja 에서 required 속성이 적용되지 않음

### ISSUE THREAD

**Issue by ashe-sparcs** [hangpark/kaistusc#140]
post_form.jinja 에서 required 속성이 적용되지 않아서 (대표적으로 제목이 required인데 빈칸이어도 포스트 생성됨)

form validation이 전혀 되지 않고 있습니다. required가 작동되게 하던지 백엔드 단에서 폼 검증이 필요합니다.

**Comment by ashe-sparcs** [comment]
novalidate 속성이 최상위 폼에 있었네요 이거랑 required랑 왜 같이 쓰는거지..

**Comment by ashe-sparcs** [comment]
novalidate 속성을 없애고, _en/_ko form 중 언어 환경에 따라 하나만 required 되도록 변경하였더니 폼 검증이 제대로 작동됩니다. 언어 환경에 따라 hide/show는 이루어졌지만, required 속성이 같이 제거/추가 되지 않아서 발생하는 문제였습니다. 풀리퀘스트가 머지되면 이슈 닫겠습니다.

**Comment by ashe-sparcs** [comment]
1

**Comment by jiggum** [comment]
1

**Comment by ashe-sparcs** [comment]
최종 1

**Comment by etranger-park** [comment]
1
