### ISSUE TITLE
댓글 업데이트

### ISSUE THREAD

**Issue by jiggum** [hangpark/kaistusc#144]
- 파일첨부 댓글 요청 ajax로(페이지변환없도록)
- 댓글 페이지네이션
- 최신댓글이 위로가도록 소팅
- <del>댓글작성후 작성된 댓글 위치로 스크롤</del>
- 삭제된 댓글 보이는 버그픽스

**Comment by jiggum** [comment]
2

**Comment by etranger-park** [comment]
삭제 기능에서 일부로 db에서 안지우는 거 아닌가요..??

**Comment by jiggum** [comment]
@etranger-park 잘못적었습니다.! is_deleted만 업데이트해주는데, 뷰에서 is_delete 제대로 반영안하고있어서 삭제된댓글들도 보여지고 있는 버그입니다.

**Comment by ashe-sparcs** [comment]
3

**Comment by jiggum** [comment]
소팅작업 반대로바꾸는작업이후에, 댓글인풋창바로아래에 최신댓글이위치하므로 스크롤기능은 필요없어졌습니다

**Comment by etranger-park** [comment]
3
