### ISSUE TITLE
총학생회 산하기구 소개 및 연락망

### ISSUE THREAD

**Issue by ashe-sparcs** [hangpark/kaistusc#159]
총학생회 산하기구를 상설위원회/특별기구/전문기구로 나누고, 각 항목에 대한 각 기구 소개 및 연락처를 조회할수 있는 탭이 필요합니다.

라고 스펙 문서에 되어 있습니다.

1. 산하기구 보드(또는 그 자식 클래스)를 총학생회 카테고리 밑에 새로 파고,
2. Contact 모델을 활용
3. 상설위원회/특별기구/전문기구 세개의 보드탭으로 나눠서 그 안에 Contact 오브젝트들을 적절히 포맷팅해서 보여준다.

같이 진행하면 될듯합니다.

**Comment by ashe-sparcs** [comment]
5

**Comment by etranger-park** [comment]
4

**Comment by jiggum** [comment]
3

**Comment by etranger-park** [comment]
4
