### ISSUE TITLE
메인 페이지 노출 포스터 만들기

### ISSUE THREAD

**Issue by etranger-park** [hangpark/kaistusc#173]
- 기존에 메인페이지에 노출되어 있던 게시판들 위치에, 게시판 노출을 지우고, 메인 포스터를 노출 할 수 있도록 하고싶다고 합니다.

**Comment by etranger-park** [comment]
안받기는 심심하니 1만 줄래요....? ㅋㅋㅋㅋ
1

**Comment by ashe-sparcs** [comment]
전 ㅇㅈ합니다.

**Comment by ashe-sparcs** [comment]
전 인정합니다 ㅋㅋ
