### ISSUE TITLE
실서버 배포

### ISSUE THREAD

**Issue by ashe-sparcs** [hangpark/kaistusc#179]
1. 소스코드를 마스터 브랜치에 머지합니다.

2. 가능하다면 데이터베이스를 테스트 서버에서 마이그레이션 합니다.

3. docker, docker-compose를 이용하여 웹, 데이터베이스 서버를 실서버에 배포합니다.

**Comment by ashe-sparcs** [comment]
6

**Comment by jiggum** [comment]
7

**Comment by etranger-park** [comment]
7

**Comment by ashe-sparcs** [comment]
#181 승인되어서 머지되면 이슈 닫겠습니다.
